#version 450

layout ( local_size_x = 120, local_size_y = 1, local_size_z = 1 ) in;

layout ( binding = 0 ) buffer input_buffer
{
	uint values_in[];
};

layout ( binding = 1 ) buffer output_buffer
{
	float values_out[];
};

/* Each localinvocationindex has its x, y and z members */
void main()
{
	/** Basic calculation
	uint index = gl_LocalInvocationID.x + gl_WorkGroupID.x * 120;
	values_out[index] = values_in[index] * 1000.0;*/

}
